# Generated by Django 4.0.4 on 2022-04-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='updated',
        ),
    ]
