# Generated by Django 4.0.4 on 2022-04-30 09:57

from django.db import migrations, models
import django.template.defaulttags


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0004_cryptocurrency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='created',
            field=models.DateTimeField(default=django.template.defaulttags.now),
        ),
    ]
