# Generated by Django 4.0.4 on 2022-04-30 10:16

from django.db import migrations, models
import django.template.defaulttags


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0007_remove_cryptocurrency_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='created',
            field=models.DateTimeField(default=django.template.defaulttags.now, null=True),
        ),
    ]
