# Generated by Django 4.0.4 on 2022-04-30 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto_app', '0007_cryptocurrency_created_cryptocurrency_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('footPrint', models.FloatField(null=True)),
                ('cryptoCurrency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crypto_app.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cryptoCurrency', 'value', 'date')},
            },
        ),
    ]
