# Generated by Django 4.0.4 on 2022-04-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0010_rename_user_transaction_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
