# Generated by Django 4.0.4 on 2022-04-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0011_alter_transaction_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_user',
        ),
    ]
