# Generated by Django 4.0.4 on 2022-04-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0012_remove_transaction_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
